# gestion/migrations/0001_initial.py
# Esta es una migración de Django autogenerada.
# Define la estructura inicial de la base de datos para los modelos de la aplicación 'gestion'.
# Contiene las operaciones para crear las tablas de los modelos Cliente, Servicio, Vehiculo y OrdenReparacion.

# Generated by Django 5.2.6 on 2025-09-16 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Clase de migración inicial para la aplicación 'gestion'.
    """
    initial = True # Indica que esta es la migración inicial para la aplicación.

    dependencies = [
    ] # Lista de dependencias de otras migraciones.

    operations = [
        # Operación para crear el modelo 'Cliente'.
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        # Operación para crear el modelo 'Servicio'.
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        # Operación para crear el modelo 'Vehiculo'.
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='gestion.cliente')),
            ],
        ),
        # Operación para crear el modelo 'OrdenReparacion'.
        migrations.CreateModel(
            name='OrdenReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ingresado', 'Ingresado'), ('en_progreso', 'En Progreso'), ('finalizado', 'Finalizado')], default='ingresado', max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('servicios', models.ManyToManyField(related_name='ordenes_reparacion', to='gestion.servicio')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_reparacion', to='gestion.vehiculo')),
            ],
        ),
    ]
