# gestion/migrations/0002_alter_ordenreparacion_monto_total_and_more.py
# Esta es una migración de Django autogenerada.
# Modifica los campos 'monto_total' en el modelo OrdenReparacion y 'precio' en el modelo Servicio,
# ajustando su precisión decimal a 0.

# Generated by Django 5.2.6 on 2025-09-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Clase de migración para ajustar campos decimales.
    """
    dependencies = [
        ('gestion', '0001_initial'), # Depende de la migración inicial de la aplicación 'gestion'.
    ]

    operations = [
        # Operación para alterar el campo 'monto_total' del modelo 'OrdenReparacion'.
        # Se cambia 'decimal_places' a 0, lo que significa que no habrá decimales.
        migrations.AlterField(
            model_name='ordenreparacion',
            name='monto_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        # Operación para alterar el campo 'precio' del modelo 'Servicio'.
        # Se cambia 'decimal_places' a 0, lo que significa que no habrá decimales.
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
