# Generated by Django 5.2.6 on 2025-09-16 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_ordenreparacion_monto_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='ordenreparacion',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name': 'Orden de Reparación', 'verbose_name_plural': 'Órdenes de Reparación'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['nombre'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['patente'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='ordenreparacion',
            name='estado',
            field=models.CharField(choices=[('ingresado', 'Ingresado'), ('en_progreso', 'En Progreso'), ('finalizado', 'Finalizado')], default='ingresado', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordenreparacion',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='ordenreparacion',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Salida'),
        ),
        migrations.AlterField(
            model_name='ordenreparacion',
            name='monto_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Monto Total'),
        ),
        migrations.AlterField(
            model_name='ordenreparacion',
            name='servicios',
            field=models.ManyToManyField(related_name='ordenes_reparacion', to='gestion.servicio', verbose_name='Servicios'),
        ),
        migrations.AlterField(
            model_name='ordenreparacion',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_reparacion', to='gestion.vehiculo', verbose_name='Vehículo'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='año',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='gestion.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=10, unique=True, verbose_name='Patente'),
        ),
    ]
